#!/bin/bash
echo "Palantir Installion"

# Install Palantir
source /etc/ros/setup.bash
if [ ! -d "/opt/ros/palantir" ];
then
    mkdir /opt/ros/palantir && mkdir /opt/ros/palantir/src
    cd /opt/ros/palantir/src
    catkin_init_workspace
    git clone -b indigo-devel https://github.com/OSUrobotics/palantir.git
    cd /opt/ros/palantir
    catkin_make
fi

# Source Commands
echo "source /opt/ros/palantir/devel/setup.bash" >> /etc/ros/setup.bash
source /etc/ros/setup.bash
